[package]
name = "ipa2ru"
version = "0.2.0"
edition = "2021"
description = "Translator from IPA to russian"
authors = ["Mira Luŝajeva <miralushch@gmail.com>"]
license = "MIT"

[dependencies]
clap = { version = "3.2.15", features = ["derive"] }
