[package]
name = "ipa2ru"
version = "0.3.0"
edition = "2021"
description = "Translator from IPA to russian"
authors = ["Мира Лущаева <miralushch@gmail.com>"]
license = "MIT"

[dependencies]
clap = { version = "3.2.16", features = ["derive"] }
